pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION = 'ap-south-1'
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    def imageTag = "726661503021.dkr.ecr.ap-south-1.amazonaws.com/travelease1/payment:latest"
                    sh "docker build -t $imageTag ."
                }
            }
        }
        stage('Push to ECR') {
            steps {
                script {
                    def registry = "726661503021.dkr.ecr.ap-south-1.amazonaws.com"
                    sh "aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $registry"
                    sh "docker push 726661503021.dkr.ecr.ap-south-1.amazonaws.com/travelease1/payment:latest"
                }
            }
        }
        stage('Deploy to ECS') {
            steps {
                script {
                    // Update ECS service to use new image
                    sh "aws ecs update-service --cluster payment-cluster --service payment-service --force-new-deployment --region ap-south-1"
                }
            }
        }
    }
}
// Jenkinsfile for Payment Service
